export const SHOW_LOADER = 'SHOW_LOADER'
export const HIDDEN_LOADER = 'HIDDEN_LOADER'

export const SHOW_ALERT = 'SHOW_ALERT'

export const ALL_PRODUCTS = 'ALL_PRODUCTS'
export const PRODUCT_BY_ID = 'PRODUCT_BY_ID'
export const ADD_PRODUCT = 'ADD_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const REMOVE_PRODUCT = 'REMOVE_PRODUCT'

export const ALL_IMAGES_FROM_PRODUCT = 'ALL_IMAGES_FROM_PRODUCT'
export const ADD_IMAGES_FROM_PRODUCT = 'ADD_IMAGES_FROM_PRODUCT'
export const REMOVE_IMAGE_FROM_PRODUCT = 'REMOVE_IMAGE_FROM_PRODUCT'
export const UPDATE_IMAGE_PRINCIPAL_FROM_PRODUCT = 'UPDATE_IMAGE_PRINCIPAL_FROM_PRODUCT'

export const ALL_TAGS = 'ALL_TAGS'
